group :development, :test do
  # debug tools
  gem "binding_of_caller"
  gem "pry-byebug"
  gem "pry-doc"
  # profiling
  gem "stackprof"
  # linter
  gem "rubocop", require: false
  gem "rubocop-checkstyle_formatter", require: false
  # test
  gem "rspec"
  gem "guard"
  gem "guard-rspec"
  gem "rspec-collection_matchers"
  gem "faker"
  gem "timecop"
end

group :test do
  gem "test-prof", require: false
end
